USE ROLE EG_ENV_SALES_ENGR_FR;
USE WAREHOUSE EG_ENV_SALES_ENGR_WH;

/** Create file format & stage **/

CREATE OR REPLACE FILE FORMAT EG_ENV_SALES_PREP_DB.INGRESS.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';


CREATE OR REPLACE STAGE EG_ENV_SALES_PREP_DB.INGRESS.SALES_RAW_STAGE
  FILE_FORMAT = EG_ENV_SALES_PREP_DB.INGRESS.CSV_FORMAT;



