USE ROLE EG_ENV_SALES_ENGR_FR;
USE WAREHOUSE EG_ENV_SALES_ENGR_WH;

/** Data ingestion using Snowflake internal stages with PUT and COPY INTO commands.

1. Go to ingestion -> Add Data -> Load files in a Stage
2. Select stage: HOTEL_RAW_STAGE
3. Upload files 
**/

-- Load customers
COPY INTO EG_ENV_SALES_PREP_DB.INGRESS.customers_stg
FROM @EG_ENV_SALES_PREP_DB.INGRESS.SALES_RAW_STAGE/customers.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- Load customer master
COPY INTO EG_ENV_SALES_PREP_DB.INGRESS.customer_master_stg
FROM @EG_ENV_SALES_PREP_DB.INGRESS.SALES_RAW_STAGE/customer_master.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- Load products
COPY INTO EG_ENV_SALES_PREP_DB.INGRESS.products_stg
FROM @EG_ENV_SALES_PREP_DB.INGRESS.SALES_RAW_STAGE/products.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- Load opportunities
COPY INTO EG_ENV_SALES_PREP_DB.INGRESS.opportunities_stg
FROM @EG_ENV_SALES_PREP_DB.INGRESS.SALES_RAW_STAGE/opportunities.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- Load orders
COPY INTO EG_ENV_SALES_PREP_DB.INGRESS.orders_stg
FROM @EG_ENV_SALES_PREP_DB.INGRESS.SALES_RAW_STAGE/orders.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);
