/** Setup Databases, Schemas, Warehouses & Roles using ACCOUNTADMIN privileges **/

-- Database & warehouse for Data Model Preparation including data load & transformations
CREATE DATABASE EG_ENV_SALES_PREP_DB;
-- Landing Layer
CREATE SCHEMA EG_ENV_SALES_PREP_DB.INGRESS;
-- Base/Data Model Layer
CREATE SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL;

-- Database & warehouse for Data Consumption
CREATE DATABASE EG_ENV_SALES_ANALYTICS_DB;
-- Inner Pre-report Layer including business logic under the consumption views
CREATE SCHEMA EG_ENV_SALES_ANALYTICS_DB.PRE_REPORT;
-- Reporting Layer exposed to users
CREATE SCHEMA EG_ENV_SALES_ANALYTICS_DB.REPORT;



-- REMOVE ALL PUBLIC ACCESS
REVOKE USAGE ON DATABASE EG_ENV_SALES_PREP_DB FROM ROLE PUBLIC;
REVOKE USAGE ON DATABASE EG_ENV_SALES_ANALYTICS_DB FROM ROLE PUBLIC;

REVOKE USAGE ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB FROM ROLE PUBLIC;
REVOKE USAGE ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB FROM ROLE PUBLIC;




-- Roles specific to databases & accesses
CREATE ROLE EG_ENV_SALES_ENGR_FR;              -- RW on PREP DB
CREATE ROLE EG_ENV_SALES_READER_FR;            -- RO on PREP DB
CREATE ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;    -- RW on ANALYTICS DB
CREATE ROLE EG_ENV_SALES_ANALYTICS_READER_FR;  -- RO on ANALYTICS DB



-- Warehouse for each role
CREATE WAREHOUSE EG_ENV_SALES_ENGR_WH 
    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

CREATE WAREHOUSE EG_ENV_SALES_READER_WH 
    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

CREATE WAREHOUSE EG_ENV_SALES_ANALYTICS_ENGR_WH 
    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

CREATE WAREHOUSE EG_ENV_SALES_ANALYTICS_READER_WH 
    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;


-- Grant write role for PREP DB
-- Visibility
GRANT USAGE ON DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_ENGR_FR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_ENGR_FR;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_ENGR_FR;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ENGR_FR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ENGR_FR;

-- DML on both schemas
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.INGRESS
    TO ROLE EG_ENV_SALES_ENGR_FR;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.INGRESS
    TO ROLE EG_ENV_SALES_ENGR_FR;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ENGR_FR;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ENGR_FR;

-- DDL 
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE SEQUENCE, CREATE FUNCTION, CREATE STREAM, CREATE TASK,
      CREATE PROCEDURE  
    ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_ENGR_FR;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE SEQUENCE, CREATE FUNCTION, CREATE STREAM, CREATE TASK,
      CREATE PROCEDURE  
    ON FUTURE SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_ENGR_FR;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE EG_ENV_SALES_ENGR_WH 
    TO ROLE EG_ENV_SALES_ENGR_FR;


-- Grant read role for PREP DB
-- Visibility
GRANT USAGE ON DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_READER_FR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_READER_FR;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EG_ENV_SALES_PREP_DB 
    TO ROLE EG_ENV_SALES_READER_FR;

-- Read-only
GRANT SELECT ON ALL TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.INGRESS 
    TO ROLE EG_ENV_SALES_READER_FR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.INGRESS 
    TO ROLE EG_ENV_SALES_READER_FR;

GRANT SELECT ON ALL TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL 
    TO ROLE EG_ENV_SALES_READER_FR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL 
    TO ROLE EG_ENV_SALES_READER_FR;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE EG_ENV_SALES_READER_WH 
    TO ROLE EG_ENV_SALES_READER_FR;



-- Grant write role for ANALYTICS DB
-- Visibility
GRANT USAGE ON DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;

-- DML
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.PRE_REPORT
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.PRE_REPORT
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.REPORT
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.REPORT
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;

-- DDL 
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE SEQUENCE, CREATE FUNCTION, CREATE STREAM, CREATE TASK 
    ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE SEQUENCE, CREATE FUNCTION, CREATE STREAM, CREATE TASK 
    ON FUTURE SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE EG_ENV_SALES_ANALYTICS_ENGR_WH 
    TO ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR;


-- Grant read role for ANALYTICS DB
-- Visibility
GRANT USAGE ON DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE EG_ENV_SALES_ANALYTICS_DB 
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

GRANT USAGE ON DATABASE EG_ENV_SALES_PREP_DB
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

GRANT USAGE ON SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

-- Read-only
GRANT SELECT ON ALL TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

GRANT SELECT ON FUTURE TABLES IN SCHEMA EG_ENV_SALES_PREP_DB.BASE_MODEL
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

GRANT SELECT ON ALL VIEWS IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.PRE_REPORT
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.PRE_REPORT
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

GRANT SELECT ON ALL VIEWS IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.REPORT 
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EG_ENV_SALES_ANALYTICS_DB.REPORT 
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE EG_ENV_SALES_ANALYTICS_READER_WH 
    TO ROLE EG_ENV_SALES_ANALYTICS_READER_FR;




/** Setup Users **/

-- User for developing data model & views
CREATE USER ENGINEER
  PASSWORD = 'Engineer!123'
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE EG_ENV_SALES_ENGR_FR TO USER ENGINEER;
GRANT ROLE EG_ENV_SALES_ANALYTICS_ENGR_FR TO USER ENGINEER;


-- User for consuming views
CREATE USER CONSUMER
  PASSWORD = 'Consumer!123'
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE EG_ENV_SALES_ANALYTICS_READER_FR TO USER CONSUMER;






